name: DNS
description: DNS
dns: {}


dns:
  # 转发规则
  forward:
    # --- BiliBili ---
    - domain_wildcard:
        match: 'upos-sz-mirrorali.bilivideo.com'
        value: quic://dns.alidns.com
    - domain_wildcard:
        match: 'upos-sz-mirrorali?.bilivideo.com'
        value: quic://dns.alidns.com
    - domain_wildcard:
        match: 'upos-sz-mirrorali??.bilivideo.com'
        value: quic://dns.alidns.com
    - domain_wildcard:
        match: 'upos-sz-mirrorbos.bilivideo.com'
        value: 180.76.76.76
    - domain_wildcard:
        match: 'upos-sz-mirrorcos.bilivideo.com'
        value: https://doh.pub/dns-query
    - domain_wildcard:
        match: 'upos-sz-mirrorcos?.bilivideo.com'
        value: https://doh.pub/dns-query
    - domain_wildcard:
        match: 'upos-sz-mirrorcos??.bilivideo.com'
        value: https://doh.pub/dns-query
    - domain_wildcard:
        match: 'upos-sz-upcdnbd??.bilivideo.com'
        value: 180.76.76.76
    - domain_wildcard:
        match: 'upos-sz-upcdntx.bilivideo.com'
        value: https://doh.pub/dns-query

    # --- Modify Contents  ---
    - domain:
        match: "blog.google"
        value: 119.29.29.29
    - domain:
        match: "googletraveladservices.com"
        value: 119.29.29.29
    - domain:
        match: "dl.google.com"
        value: 119.29.29.29
    - domain:
        match: "dl.l.google.com"
        value: 119.29.29.29
    - domain:
        match: "clientservices.googleapis.com"
        value: 119.29.29.29
    - domain:
        match: "update.googleapis.com"
        value: 119.29.29.29
    - domain:
        match: "translate.googleapis.com"
        value: 119.29.29.29
    - domain:
        match: "fonts.googleapis.com"
        value: 119.29.29.29
    - domain:
        match: "fonts.gstatic.com"
        value: 119.29.29.29
    - domain:
        match: "stun.l.google.com"
        value: system
    - domain_wildcard:
        match: "stun?.l.google.com"
        value: system

    # --- Router Admin Panel ---
    - domain_wildcard:
        match: '*.id.ui.direct'
        value: system
    - domain:
        match: 'unifi.local'
        value: system
    - domain:
        match: 'amplifi.lan'
        value: system
    - domain:
        match: 'router.synology.com'
        value: system
    - domain:
        match: 'sila.razer.com'
        value: system
    - domain:
        match: 'router.asus.com'
        value: system
    - domain:
        match: 'routerlogin.net'
        value: system
    - domain:
        match: 'orbilogin.com'
        value: system
    - domain:
        match: 'www.LinksysSmartWiFi.com'
        value: system
    - domain:
        match: 'LinksysSmartWiFi.com'
        value: system
    - domain:
        match: 'myrouter.local'
        value: system
    - domain:
        match: 'instant.arubanetworks.com'
        value: system
    - domain:
        match: 'setmeup.arubanetworks.com'
        value: system
    - domain:
        match: 'www.miwifi.com'
        value: system
    - domain:
        match: 'miwifi.com'
        value: system
    - domain:
        match: 'mediarouter.home'
        value: system
    - domain:
        match: 'tplogin.cn'
        value: system
    - domain:
        match: 'tplinklogin.net'
        value: system
    - domain:
        match: 'tplinkwifi.net'
        value: system
    - domain:
        match: 'melogin.cn'
        value: system
    - domain:
        match: 'falogin.cn'
        value: system
    - domain:
        match: 'tendawifi.com'
        value: system
    - domain:
        match: 'leike.cc'
        value: system
    - domain:
        match: 'zte.home'
        value: system
    - domain:
        match: 'p.to'
        value: system
    - domain:
        match: 'phicomm.me'
        value: system
    - domain:
        match: 'hiwifi.com'
        value: system
    - domain:
        match: 'peiluyou.com'
        value: system
    - domain:
        match: '_hotspot_.m2m'
        value: system
    - domain:
        match: 'hotspot.cslwifi.com'
        value: system

  # 主机映射
  hosts:
    # > IPv6
    ip6-localhost: ::1
    ip6-loopback: ::1
    ip6-localnet: fe00::0
    ip6-mcastprefix: ff00::0
    ip6-allnodes: ff02::1
    ip6-allrouters: ff02::2
    ip6-allhosts: ff02::3

    # > Encrypted DNS
    dns.google:
      - 8.8.8.8
      - 8.8.4.4
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    dns64.dns.google:
      - 2001:4860:4860::6464
      - 2001:4860:4860::64
    cloudflare-dns.com:
      - 104.16.249.249
      - 104.16.248.249
      - 2606:4700::6810:f8f9
      - 2606:4700::6810:f9f9
    1dot1dot1dot1.cloudflare-dns.com:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1001
      - 2606:4700:4700::1111
    one.one.one.one:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1001
      - 2606:4700:4700::1111
    dns.alidns.com:
      - 223.5.5.5
      - 223.6.6.6
      - 2400:3200:baba::1
      - 2400:3200::1
    doh.pub:
      - 1.12.12.12
      - 120.53.53.53
    dot.pub:
      - 1.12.12.12
      - 120.53.53.53
    doh.360.cn:
      - 23.6.48.18
      - 112.65.69.15
    dot.360.cn:
      - 101.198.198.198
      - 101.198.199.200
      - 101.198.192.33
      - 112.65.69.15
    dns.twnic.tw:
      - 101.101.101.101
      - 2001:de4::101
      - 2001:de4::102
    ordns.he.net:
      - 74.82.42.42
      - 2001:470:20::2

    # > Modify Contents
    talk.google.com: 108.177.125.188
    mtalk.google.com:
      - 108.177.125.188
      - 2404:6800:4008:c07::bc
      - 142.250.31.188
    alt1-mtalk.google.com:
      - 3.3.3.3
      - 2607:f8b0:4023:c0b::bc
      - 64.233.171.188
    alt2-mtalk.google.com:
      - 3.3.3.3
      - 142.250.115.188
    alt3-mtalk.google.com:
      - 74.125.200.188
      - 173.194.77.188
    alt4-mtalk.google.com:
      - 74.125.200.188
      - 173.194.219.188
    alt5-mtalk.google.com:
      - 3.3.3.3
      - 2607:f8b0:4023:1::bc
      - 142.250.112.188
    alt6-mtalk.google.com:
      - 3.3.3.3
      - 172.217.197.188
    alt7-mtalk.google.com:
      - 74.125.200.188
      - 2607:f8b0:4002:c03::bc
      - 108.177.12.188
    alt8-mtalk.google.com: 3.3.3.3


